[package]
name = "grablink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daggy = "0.8.0"
once_cell = "1.18.0"
regex = "1.10.1"
egg = "0.9.5"
itertools = "0.12.0"

[profile.release]
debug = true
